### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Meganium97** [mogzol/BrawlBuilder#13]
Hey, I was just going to use this, and I have some questions.
1. Would it work with Project+? I'm not sure if that one's based on BrawlEx
2. Why hasn't there been any action in a while?
3. Are there still crashes on alt stages?
Thank you for your time.

**Comment by mogzol** [comment]
Hi, I haven't tested this with Project+, I don't think that uses BrawlEx so it might work. As for why there hasn't been any updates for this in a while, sorry, I kind of lost interest in Project M and don't have the free time necessary to try and fix the remaining issues. It involves a lot of debugging through Dolphin which can be really time consuming.

Other people are welcome to contribute, fixing the issues is mostly a matter of figuring out what patches need to be made to the vanilla Project M/P+/whatever gecko codes so that they work properly when everything is on the disk rather than loading off the SD card. I'll happily review any pull requests if people find fixes.

Sorry, I know that's probably not the answer you're looking for, but that's whats going on.

**Comment by Meganium97** [comment]
I just checked in with the Project+ discord, and que the bot saying, "It's not currently possible to use brawlbuilder or a similar tool to build a Project+ ISO. Certain codes that P+ uses are not compatible with ISO building".
